[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

bytemuck = { version = "1.12", features = [ "derive" ] }
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
winit = "0.28"
image = "0.24"
pollster = "0.2"