[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
cgmath = "0.18"
toml = "0.7"
serde = "1.0"
crossbeam-channel = "0.5"
anyhow = "1.0"
mlua = { version = "0.8", features = ["lua54", "vendored"] }