[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
glam = "0.23"
toml = "0.7"
serde = "1.0"
byte = "0.2"
mlua = { version = "0.8", features = ["lua54", "vendored"] }
uflow = "0.7"
phf = { version = "0.11", features = ["macros"] }
profiling = "1.0"